a=input("請輸入時間1(時:分:秒):")
b=int(input("請輸入時間2(秒):"))
c=a.split(":")
d=int(c[0])*60*60
h=int(c[1])*60
j=int(c[2])
print("時間1(",a,")格式轉換後為",d+h+j,"秒")
e=b//60
f=e//60
g=b%60
k=e-f*60
print("時間2(",b,"秒)=",f,":",k,":",g)